project:
  type: book

book:
  title: "Methods in evolutionary ecology â€“ bioinformatics and data analysis"
  author: 
    - id: 1
      name: Stefanos Siozios
      email: stefanos.siozios@zoologie.uni-halle.de
    - id: 2
      name: Michael Gerth
      email: michael.gerth@zoologie.uni-halle.de
  downloads: [pdf]
  chapters:
    - index.qmd
    - part: "`R`"
      chapters:
        - Rintro.qmd
        - tidyverse.qmd
    - part: "UNIX"
    - part: "Phylogenetics" 
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

