project:
  type: book

book:
  title: "Methods in evolutionary ecology WS25/26"
  author: 
    - id: 1
      name: Stefanos Siozios
      email: stefanos.siozios@zoologie.uni-halle.de
    - id: 2
      name: Michael Gerth
      email: michael.gerth@zoologie.uni-halle.de
  downloads: [pdf]
  repo-url: https://github.com/gerthmicha/MEE-WS25-26
  chapters:
    - index.qmd
    - part: "`R`"
      chapters:
        - Rintro1.qmd
        - Rintro2.qmd
        - Rintro3.qmd
        - tidyverse.qmd
        - ggplot.qmd
    - part: "UNIX"
    - part: "Phylogenetics" 
    - part: "Microbiome"
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    df-print: paged
  pdf:
    documentclass: scrreprt
    df-print: paged
    
editor: visual

