project:
  type: book

book:
  title: "MEE-WS25-26"
  author: "Stefanos Siozios & Michael Gerth"
  date: "WS 25/26"
  chapters:
    - index.qmd
    - Rintro.qmd
    - tidyverse.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

