project:
  type: book

book:
  title: "Methods in evolutionary ecology WS25/26"
  author: 
    - id: 1
      name: Stefanos Siozios
      email: stefanos.siozios@zoologie.uni-halle.de
    - id: 2
      name: Michael Gerth
      email: michael.gerth@zoologie.uni-halle.de
  downloads: [pdf]
  repo-url: https://github.com/gerthmicha/MEE-WS25-26
  chapters:
    - index.qmd
    - part: "`R`"
      chapters:
        - Rintro1.qmd
        - Rintro2.qmd
        - Rintro3.qmd
        - tidyverse.qmd
        - ggplot.qmd
    - part: "UNIX"
      chapters:
        - unixIntro.qmd
        - unixPart1.qmd
        - unixPart2.qmd
        - unixPart3.qmd
    - part: "NGSanalysis"
      chapters:
        - NGSanalysisPart1.qmd
        - NGSanalysisPart2.qmd
        - NGSanalysisPart3.qmd
    - part: "Phylogenetics" 
      chapters:
        - phylo1.qmd
        - phylo2.qmd
        - phylo3.qmd
        - phylo4.qmd
        - phylo6.qmd

format:
  html:
    theme: cosmo
    df-print: paged
  pdf:
    documentclass: scrreprt
    df-print: kable
    execute:
      eval: false
    
editor: visual

